/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "secondary-container": "#d6e0f6",
        "outline": "#717880",
        "primary": "#385d8e",
        "on-secondary-fixed": "#121c2c",
        "secondary-fixed-dim": "#bdc7dc",
        "surface-container": "#edeeef",
        "outline-variant": "#c1c7d0",
        "surface": "#f8f9fa",
        "on-surface-variant": "#41474f",
        "primary-fixed-dim": "#a5c8ff",
        "on-background": "#191c1d",
        "secondary": "#555f71",
        "tertiary": "#7d5400",
        "inverse-on-surface": "#f0f1f2",
        "surface-tint": "#3b6090",
        "surface-container-low": "#f3f4f5",
        "on-tertiary-fixed": "#281800",
        "surface-bright": "#f8f9fa",
        "surface-dim": "#d9dadb",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "background": "#f8f9fa",
        "on-error": "#ffffff",
        "secondary-fixed": "#d9e3f9",
        "inverse-primary": "#a5c8ff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#614000",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#ffddb0",
        "surface-variant": "#e1e3e4",
        "on-secondary-container": "#596376",
        "primary-container": "#5276a8",
        "tertiary-container": "#9a6c17",
        "on-secondary-fixed-variant": "#3d4759",
        "surface-container-highest": "#e1e3e4",
        "on-surface": "#191c1d",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#204877",
        "on-primary-fixed": "#001c3a",
        "inverse-surface": "#2e3132",
        "on-primary-container": "#fefcff",
        "tertiary-fixed-dim": "#f6bc62",
        "primary-fixed": "#d4e3ff",
        "surface-container-high": "#e7e8e9",
        "on-tertiary-container": "#fffbff"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
